Update on_opensuse.md
crystal-lang/crystal-website pull request #139
Opened 2021-05-01 16:31 UTC by Stig124

OpenSUSE din't have up to date installation instructions
This PR fixes those issues

2021-05-01 21:37 UTC, straight-shoota requested changes
The generic installer script should also work on openSUSE now. The instructions for then installer should be the same as for the other OBS-based distros.
Could you please add that, too?
I think the more explicit approach should be labeled as "Manual setup" as with other rpm and deb based instructions.

2021-05-01 21:37 UTC, straight-shoota commented on install/on_opensuse.md
> +On OpenSUSE, Crystal can be installed from the official repo using Zypper.
```suggestion
On OpenSUSE, Crystal can be installed from the official repository hosted on the [Open Build Service](https://build.opensuse.org) using Zypper.
```

2021-05-01 23:26 UTC, Stig124 commented
I was thinking about that, but I don't think it is time, let me explain :

Zypper is a vendor-sticky package manager, people which have used `bintray` repo in the past might have difficulty changing repos when update come depending on zypper config. The last step I laid out, in my eyes, is really important because it preemptively mitigate the vendor-stickyness issue

Before adding the script as main install method, I think it is fair to wait some time for a majority of peoples to migrate repo.

2021-05-02 13:08 UTC, straight-shoota approved these changes
Okay, sounds good.

2021-05-10 10:32 UTC, straight-shoota approved these changes

2021-05-10 12:31 UTC, beta-ziliani reviewed
Do we have a way to test this @straight-shoota ?

2021-05-10 13:06 UTC, straight-shoota commented
The installation instructions themselves are impossible to test because they need human interpretation.

A formalized test is in [distribution-scripts](https://github.com/crystal-lang/distribution-scripts/blob/master/packages/test/opensuse.bats), based on the installer script (which essentially applies the instruction in a generic way).

2021-05-10 14:17 UTC, beta-ziliani commented
:rofl:  of course I didn't mean to test the instructions, but the lines therein :-)

2021-05-10 14:18 UTC, beta-ziliani approved these changes

2021-05-10 14:52 UTC, merged

2021-05-10 14:52 UTC, straight-shoota commented
Merci @Stig124