Adding Crys
crystal-lang/crystal-website pull request #491
Opened 2023-07-28 14:29 UTC by beta-ziliani

2023-07-31 07:53 UTC, caspiano requested changes

2023-07-31 07:53 UTC, caspiano commented on _pages/media.html
> +          Meet Crys, the mascot of Crystal. It's smart and likes shinny things, so feed it with your best shards!
```suggestion
          Meet Crys, the mascot of Crystal. It's smart and likes shiny things, so feed it with your best shards!
```

2023-07-31 22:48 UTC, matiasgarciaisaia approved these changes
:+1:

2025-09-25 19:31 UTC, matiasgarciaisaia commented
Do we know why we never merged this one?

2025-09-25 19:57 UTC, straight-shoota commented
There was some discussion about the usage terms, which unfortunately never got resolved. We even tried to pick it up again a couple months back but this is still where we are...

Link to private slack channel: https://manas.slack.com/archives/C02MH0NCV/p1742297260371819

2025-09-29 20:26 UTC, matiasgarciaisaia commented
As we discussed, I've added the logos without further expanding the guidelines.

2025-09-30 18:29 UTC, merged