Add Install page
crystal-lang/crystal-website pull request #540
Opened 2023-11-24 14:24 UTC by straight-shoota

Implements a new `Install` page overview and updates the install subpages, drastically cutting down on duplicate content there.

The main page has simple instructions directly available for a ton of installation mechanisms, as well as direct links to further instructions and package information.
The page is pretty plain and simple (no interactive selection as we had previously toyed with), but it's very usable and rich on information. A clear structure based on the operating system and then categorized by the type of package provider (official Crystal packages, system packages, 3rd party community packages) enables finding useful solutions easily.

The sub pages are trimmed down and each one has now exactly one purpose, detailing the installation instructions for the official packages on a specific operating system, or instructions for installation with a specific package manager. There are no longer individual pages for specific linux distribution which all shared more or less the same code. They redirect to the linux overview now, which should even be more helpful.

Further enhancements of this page could introduce some kind of platform-detection mechanism to highlight the current operating system, for example to pin instructions for the current OS to the top of the page.

Depends on #529 and #534

2023-11-24 14:52 UTC, beta-ziliani commented
Love the concept so far! 🤩

2023-12-14 22:29 UTC, straight-shoota commented
Screenshot after some design iterations with @jkicillof:

![grafik](https://github.com/crystal-lang/crystal-website/assets/466378/9ba1bf82-efb5-4d69-bac9-b539477206fa)

2024-01-15 21:02 UTC, straight-shoota commented
I have incorporated the relevant visual changes from #547 into this branch, which is mostly responsive layout.
I kept the plain (i.e. not button) styling for the titles, and did not port any of the internal refactorings.

2024-01-17 19:08 UTC, straight-shoota commented
I have rebased on the relaunch branch without any dependency PRs. This should be ready to merge now.

![grafik](https://github.com/crystal-lang/crystal-website/assets/466378/75be211d-3f3c-42b3-82d2-c8e8dff53212)

2024-01-18 14:22 UTC, beta-ziliani requested changes
Overall I love it. I have several improvements to require (or suggest, happy to discuss them), in order of importance:
 - Shouldn't "Build from Source" and "Nightly" be in the first section (Crystal)? The tarball _is_ building from source, so it's weird to have it twice and disconnected. Alternatively, we can put both, the "tarball" and "nightly" in each relevant section (Linux, macOS, Window (which is missing)) pointing at the corresponding #section in the page.
 - The info box for 84codes' `packagecloud.io` should go in the text, as it is required information and not just additional info (as in the others).
 - Same with the internal links to specific installation modes, I think we need to link them within the text those that _require_ extra steps (instead of listing the steps), or place them in the info box if this is just additional information (like the scoop package). Then, the info about the package should be (as it is now) in the specific page instead of in the info box.
 - the color in the bash code makes no sense, better plain text. The scoop one also looks weird.
 - Can we add a green `latest` for those we know are updated? (snapcraft, installers, etc, which we control).

2024-01-18 15:58 UTC, beta-ziliani commented
One more: I like how Julia adds the tier next to the platform, maybe we can consider adding something like that

2024-01-18 20:04 UTC, straight-shoota commented
* IMO nightlies and source builds are entirely different categories. I could see nightlies being understood as just a different release channel than stable. That's usually how the nightly packages work. It probably still makes sense to have a separate overview of which package sources provide nightlies because not all of them do.
* Agreed
* Internal links will be better noticable once the updated link styles are merged.
* Updating the color scheme for the highlighter is on the TODO list. This is an independent issue.
* I'll add a version indicator for the official packages.

2024-01-19 14:10 UTC, beta-ziliani requested changes
Some minor fixes left.

I still think we can improve the consistency of the three data cells (name, instructions, info icon), when to use which and for what. And add the tier. But I will leave that for a second iteration.

2024-01-19 14:10 UTC, beta-ziliani commented on _pages/install.md
> +        <a href="https://openports.pl/path/lang/crystal" title="Crysta port on openports.pl" class="info">{% include icons/info.svg %}</a>
```suggestion
        <a href="https://openports.pl/path/lang/crystal" title="Crystal port on openports.pl" class="info">{% include icons/info.svg %}</a>
```

2024-01-19 14:10 UTC, beta-ziliani commented on _pages/install.md
> +        {% endhighlight %}
```suggestion
sudo make -C/usr/ports/devel/shards reinstall clean{% endhighlight %}
```

2024-01-19 14:19 UTC, straight-shoota commented on assets/install/version-badge.svg
> +<linearGradient id="grad" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g clip-path="url(#clip)"><rect width="100%" heig
I think GitHub primarily complains about the YAML frontmatter 😆
I'll change the file extension.

2024-01-19 17:58 UTC, beta-ziliani approved these changes
🚀

2024-01-19 17:58 UTC, beta-ziliani commented on assets/install/version-badge.svg
> +<linearGradient id="grad" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g clip-path="url(#clip)"><rect width="100%" heig
ahh! that red is not a diff! that's confusing! (although I should've noted it)

2024-01-19 18:01 UTC, merged